# disable: line-length
MD013: false

# disable: no-duplicate-heading/no-duplicate-header
MD024: false

# disable: no-inline-html
MD033: false

# disable: first-line-heading/first-line-h1
MD041: false
